class AddIndexToAllTables < ActiveRecord::Migration
  def self.up
    add_index :absences, :absence_type_id
    add_index :absence_quotas, :absence_type_id
    add_index :absence_quotas, :company_id
    add_index :absence_types, :company_id
    add_index :accidents, :company_id
    add_index :actions, :company_id
    add_index :addresses, :owner_id
    add_index :addresses, :company_id
    add_index :awards, :period_id
    add_index :awards, :person_id
    add_index :awards, :company_id
    add_index :contract_types, :company_id
    add_index :correlations, :company_id
    add_index :departments, :company_id
    add_index :divisions, :holding_company_id
    add_index :divisions, :company_id
    add_index :divisions, :department_id
    add_index :educational_institutions, :company_id
    add_index :educations, :person_id
    add_index :educations, :educational_institution_id
    add_index :educations, :company_id
    add_index :employee_shifts, :work_group_id
    add_index :employee_shifts, :company_id
    add_index :employments, :employment_type_id
    add_index :employments, :position_id
    add_index :employments, :previous_employment_id
    add_index :employment_types, :company_id
    add_index :experiences, :person_id
    add_index :experiences, :company_id
    add_index :experiences, :previous_company_id
    add_index :families, :person_id
    add_index :families, :company_id
    add_index :features, :company_id
    add_index :fingerprint_devices, :company_id
    add_index :health_details, :health_id
    add_index :holding_companies, :company_id
    add_index :honors, :person_id
    add_index :honors, :company_id
    add_index :hr_settings, :company_id
    add_index :joint_leaves, :company_id
    add_index :leaves_quotas, :company_id
    add_index :leaves_quotas, :person_id
    add_index :national_holidays, :company_id
    add_index :overtimes, :company_id
    add_index :overtimes, :person_id
    add_index :overtime_datas, :person_id
    add_index :overtime_datas, :company_id
    add_index :payroll_settings, :company_id
    add_index :people, :latest_employment_id
    add_index :people, :holding_company_id
    add_index :people, :employment_id
    add_index :people, :company_id
    add_index :people, :tax_status_id
    add_index :people, :user_id
    add_index :people, :latest_work_contract_id
    add_index :people, :next_tax_status_id
    add_index :positions, :company_id
    add_index :premia, :company_id
    add_index :premiums, :company_id
    add_index :premiums_in_companies, :premium_id
    add_index :premiums_in_companies, :company_id
    add_index :premium_in_honors, :company_id
    add_index :premium_in_honors, :premium_id
    add_index :premium_master_datas, :salary_master_data_id
    add_index :premium_master_datas, :premiums_in_company_id
    add_index :previous_companies, :company_id
    add_index :raw_presences, :reg_id
    add_index :raw_presences, :company_id
    add_index :salary_master_datas, :employment_id
    add_index :salary_master_datas, :company_id
    add_index :sections, :company_id
    add_index :shifts, :monday_time_id
    add_index :shifts, :tuesday_time_id
    add_index :shifts, :wednesday_time_id
    add_index :shifts, :thursday_time_id
    add_index :shifts, :friday_time_id
    add_index :shifts, :saturday_time_id
    add_index :shifts, :sunday_time_id
    add_index :trainings, :person_id
    add_index :users, :login
    add_index :users, :company_id
    add_index :user_companies, :company_id
    add_index :user_companies, :user_id
    add_index :violations, :person_id
    add_index :violations, :company_id
    add_index :work_contracts, :company_id
    add_index :work_contracts, :person_id
    add_index :work_contracts, :contract_type_id
    add_index :work_contracts, :previous_work_contract_id
    add_index :work_groups, :company_id
    add_index :work_groups, :division_id
    add_index :work_times, :company_id
  end

  def self.down
    remove_index :absences, :absence_type_id
    remove_index :absence_quotas, :absence_type_id
    remove_index :absence_quotas, :company_id
    remove_index :absence_types, :company_id
    remove_index :accidents, :company_id
    remove_index :actions, :company_id
    remove_index :addresses, :owner_id
    remove_index :addresses, :company_id
    remove_index :awards, :period_id
    remove_index :awards, :person_id
    remove_index :awards, :company_id
    remove_index :contract_types, :company_id
    remove_index :correlations, :company_id
    remove_index :departments, :company_id
    remove_index :divisions, :holding_company_id
    remove_index :divisions, :company_id
    remove_index :divisions, :department_id
    remove_index :educational_institutions, :company_id
    remove_index :educations, :person_id
    remove_index :educations, :educational_institution_id
    remove_index :educations, :company_id
    remove_index :employee_shifts, :work_group_id
    remove_index :employee_shifts, :company_id
    remove_index :employments, :employment_type_id
    remove_index :employments, :position_id
    remove_index :employments, :previous_employment_id
    remove_index :employment_types, :company_id
    remove_index :experiences, :person_id
    remove_index :experiences, :company_id
    remove_index :experiences, :previous_company_id
    remove_index :families, :person_id
    remove_index :families, :company_id
    remove_index :features, :company_id
    remove_index :fingerprint_devices, :company_id
    remove_index :health_details, :health_id
    remove_index :holding_companies, :company_id
    remove_index :honors, :person_id
    remove_index :honors, :company_id
    remove_index :hr_settings, :company_id
    remove_index :joint_leaves, :company_id
    remove_index :leaves_quotas, :company_id
    remove_index :leaves_quotas, :person_id
    remove_index :national_holidays, :company_id
    remove_index :overtimes, :company_id
    remove_index :overtimes, :person_id
    remove_index :overtime_datas, :person_id
    remove_index :overtime_datas, :company_id
    remove_index :payroll_settings, :company_id
    remove_index :people, :latest_employment_id
    remove_index :people, :holding_company_id
    remove_index :people, :employment_id
    remove_index :people, :company_id
    remove_index :people, :tax_status_id
    remove_index :people, :user_id
    remove_index :people, :latest_work_contract_id
    remove_index :people, :next_tax_status_id
    remove_index :positions, :company_id
    remove_index :premia, :company_id
    remove_index :premiums, :company_id
    remove_index :premiums_in_companies, :premium_id
    remove_index :premiums_in_companies, :company_id
    remove_index :premium_in_honors, :company_id
    remove_index :premium_in_honors, :premium_id
    remove_index :premium_master_datas, :salary_master_data_id
    remove_index :premium_master_datas, :premiums_in_company_id
    remove_index :previous_companies, :company_id
    remove_index :raw_presences, :reg_id
    remove_index :raw_presences, :company_id
    remove_index :salary_master_datas, :employment_id
    remove_index :salary_master_datas, :company_id
    remove_index :sections, :company_id
    remove_index :shifts, :monday_time_id
    remove_index :shifts, :tuesday_time_id
    remove_index :shifts, :wednesday_time_id
    remove_index :shifts, :thursday_time_id
    remove_index :shifts, :friday_time_id
    remove_index :shifts, :saturday_time_id
    remove_index :shifts, :sunday_time_id
    remove_index :trainings, :person_id
    remove_index :users, :login
    remove_index :users, :company_id
    remove_index :user_companies, :company_id
    remove_index :user_companies, :user_id
    remove_index :violations, :person_id
    remove_index :violations, :company_id
    remove_index :work_contracts, :company_id
    remove_index :work_contracts, :person_id
    remove_index :work_contracts, :contract_type_id
    remove_index :work_contracts, :previous_work_contract_id
    remove_index :work_groups, :company_id
    remove_index :work_groups, :division_id
    remove_index :work_times, :company_id
  end
end
